name: Build and Push to GitHub Container Registry

on:
  push:
    branches:
      - main

# for secrets.GITHUB_TOKEN 
permissions:
  packages: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # GitHub Container Registry にログイン
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Docker イメージをビルド
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/vul-apache-cve-2021-42103:latest .

      # Docker イメージをプッシュ
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/vul-apache-cve-2021-42103:latest